name: 'Docker Build Action'
description: 'Build and push docker image'

inputs:
  tag-name:
    description: 'The name of the image to produce (without tag)'
    required: true
  working-directory:
    description: 'The directory, in which the Dockerfile resides'
    required: false
    default: '.'
  docker-registry:
    description: 'Address of registry to push image to'
    required: false
    default: ''
  docker-user:
    description: 'User for logging in to registry'
    required: false
    default: ''
  docker-password:
    description: 'Password for logging in to registry'
    required: false
    default: ''
  platforms:
    description: 'The platforms, which the image shall support'
    required: false
    default: 'linux/amd64'
  push:
    description: 'Push image to registry'
    required: false
    default: false

runs:
  using: "composite"
  steps:
    -
      name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    -
      name: Set up Docker Buildx
      id: buildx-setup
      uses: docker/setup-buildx-action@v2
      with:
        use: false
        driver-opts: |
          network=host
    -
      name: Login to Docker Registry
      uses: docker/login-action@v2
      if: inputs.push == 'true' && inputs.docker-user != '' && inputs.docker-password != ''
      with:
        registry: ${{ inputs.docker-registry }}
        username: ${{ inputs.docker-user }}
        password: ${{ inputs.docker-password }}
    -
      name: Define absolute tag name
      id: tag-definition
      shell: bash
      run: |
        TAG=$TAG_NAME
        [[ "$REGISTRY" != "" ]] && TAG=$REGISTRY/$TAG_NAME
        echo "tag=$TAG" >> "$GITHUB_OUTPUT"
      env:
        REGISTRY: ${{ inputs.docker-registry }}
        TAG_NAME: ${{ inputs.tag-name }}
    -
      name: Build and push
      uses: docker/build-push-action@v4
      with:
        builder: ${{ steps.buildx-setup.outputs.name }}
        context: ${{ inputs.working-directory }}
        platforms: ${{ inputs.platforms }}
        push: ${{ inputs.push }}
        tags: ${{ steps.tag-definition.outputs.tag }}
