name: Test Github Action
on:
  push:
  pull_request:

jobs:
  Test-Build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Build Test Image
        uses: ./
        with:
          tag-name: dummy
          working-directory: test
  Test-Build-Extended:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Build Test Image
        uses: ./
        with:
          docker-registry: registry.example.org
          tag-name: dummy
          working-directory: test
          platforms: 'linux/amd64,linux/arm64'
  Test-Push:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Start registry
        id: registry
        run: |
          docker run --rm -d -v ${{ github.workspace }}/test:/tmp/auth:ro -e REGISTRY_AUTH=htpasswd -e REGISTRY_AUTH_HTPASSWD_REALM=test -e REGISTRY_AUTH_HTPASSWD_PATH=/tmp/auth/auth -p 5000:5000 registry:2
      -
        name: Build Test Image
        uses: ./
        with:
          tag-name: dummy:try
          working-directory: test
          docker-registry: localhost:5000
          docker-user: test
          docker-password: test
          push: true
      -
        name: Try Pull Image
        run: |
          docker image pull localhost:5000/dummy:try